spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/2fa
    username: roshan
    password: @roshan123..
  jpa:
    hibernate:
      ddl-auto: update